export default [
  {
    id: 37,
    name: 'Garen',
    alias: 'Force de Demacia',
    slug: 'garen',
    description: 'Garen est un guerrier fier et noble qui fait partie du Détachement hardi. Héritier des Crownguard, la famille chargée de défendre Demacia et ses idéaux, il est apprécié par ses compatriotes et respecté par ses ennemis. Équipé d\'une armure résistante à la magie et d\'une épée large, Garen affronte sans faillir les mages et les sorciers dans un véritable tourbillon d\'acier.',
    picture: '../assets/champions/garen.jpg',
    release_date: '2010-04-27',
    role: '1',
    type: '2',
  },
  {
    id: 75,
    name: 'Lux',
    alias: 'Dame de lumière',
    slug: 'lux',
    description: 'Luxanna Crownguard est originaire de Demacia, un royaume isolationniste où la magie inspire la peur et la méfiance. Capable de plier la lumière à sa volonté, elle a grandi dans la crainte d\'être un jour exilée et a été contrainte de dissimuler son pouvoir pour préserver l\'honneur de sa famille. Cependant, l\'optimisme et la ténacité de Lux l\'ont conduite à accepter ses talents uniques, et elle les emploie désormais secrètement pour le bénéfice de sa patrie.',
    picture: '../assets/champions/lux.jpg',
    release_date: '2010-10-19',
    role: '5',
    type: '3',
  },
  {
    id: 81,
    name: 'Miss Fortune',
    alias: 'Chasseuse de primes',
    slug: 'missfortune',
    description: 'Capitaine de Bilgewater réputée pour sa beauté et crainte pour sa cruauté, Sarah Fortune est une personnalité qui détonne au milieu des criminels endurcis qui arpentent la cité portuaire. Enfant, elle assista au massacre de sa famille par Gangplank, le roi des pillards, et elle prit sa revanche des années plus tard, faisant exploser son navire alors qu\'il se trouvait à bord. Ceux qui la sous-estiment découvrent un adversaire imprévisible et séduisant... avant de prendre une ou deux balles dans les entrailles.',
    picture: '../assets/champions/missfortune.jpg',
    release_date: '2010-09-08',
    role: '4',
    type: '6',
  },
];